# .github/workflows/build-and-push-docker.yml
name: Build and Push Rust MUSL Builder Image

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual triggering

env:
  # Replace 'your-github-username' with your actual GitHub username or organization name
  # Replace 'rust-musl-builder' with the name of this repository
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/rust-musl-builder

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push images to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long,prefix=sha- # Example: sha-abcdef1234
            type=ref,event=branch # Example: main, master

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Path to the Dockerfile's build context (current directory)
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Use GitHub Actions cache for Docker layers
          cache-to: type=gha,mode=max # Push Docker layers to GHA cache
